# JVM内存配置
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError

# AndroidX 兼容
android.useAndroidX=true
android.enableJetifier=true

# Clash代理配置，用于拉取谷歌Maven、NDK、AGP依赖
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7897
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7897