const fs = require('fs');
function w(s) { return s + '\n'; }
let md = '';

// ======== Title ========
md += w('# TypeORM Migration 方案');
md += w('');
md += w('> 项目: Happy Every Day (天天开心)');
md += w('> 数据库: PostgreSQL 15');
md += w('> ORM: TypeORM v0.3.x');
md += w('> NestJS 版本: v11');
md += w('');
md += w('---');
md += w('');

// ======== 1. 安装依赖 ========
md += w('## 1. 安装依赖');
md += w('');
md += w('```bash');
md += w('npm install @nestjs/typeorm typeorm pg');
md += w('```');
md += w('');
md += w('> 当前 package.json 使用 module: nodenext，TypeORM v0.3.x 完全兼容。');
md += w('');

// ======== 2. 目录结构 ========
md += w('---');
md += w('');
md += w('## 2. Migration 目录结构');
md += w('');
md += w('```');
md += w('backend/');
md += w('  src/database/');
md += w('    migrations/');
md += w('      0000-CreateExtensions.ts');
md += w('      0001-CreateUsersTable.ts');
md += w('      0002-CreateUserProfilesTable.ts');
md += w('      0003-CreateDailyPlansTable.ts');
md += w('      0004-CreateInterestsTable.ts');
md += w('      0005-CreateUserInterestsTable.ts');
md += w('      0006-CreateActivitiesTable.ts');
md += w('      0007-CreateMoodLogsTable.ts');
md += w('      0008-CreateJournalsTable.ts');
md += w('      0009-CreateFavoritesTable.ts');
md += w('      0010-CreateIndexesAndTriggers.ts');
md += w('      0011-xxxx  (后续增量)');
md += w('    data-source.ts');
md += w('    database.module.ts');
md += w('  ormconfig.ts');
md += w('  .env');
md += w('```');
md += w('');

// ======== 3. 命名规范 ========
md += w('---');
md += w('');
md += w('## 3. 命名规范');
md += w('');
md += w('### 3.1 文件命名');
md += w('');
md += w('[顺序号]-[Action][EntityName].ts');
md += w('');
md += w('| 部分 | 规则 | 示例 |');
md += w('|------|------|------|');
md += w('| 顺序号 | 4位数字，全局递增 | 0001, 0002 |');
md += w('| Action | Create / Alter / Drop / AddIndex | Create |');
md += w('| EntityName | 帕斯卡命名 | UsersTable |');
md += w('');
md += w('> 也可以使用时间戳格式（如 1740000000000），两种风格均可，保持一致即可。');
md += w('');
md += w('### 3.2 类命名');
md += w('');
md += w('```typescript');
md += w('export class CreateUsersTable0001 implements MigrationInterface {');
md += w("  name = 'CreateUsersTable0001';");
md += w('}');
md += w('```');
md += w('');
md += w('### 3.3 表名约定');
md += w('');
md += w('| 规则 | 说明 | 示例 |');
md += w('|------|------|------|');
md += w('| 全小写 + 下划线 | 与 DDL 一致 | daily_plans |');
md += w('| 单数形式 | 推荐 | user, interest |');
md += w('| 避免保留字 | 避开 SQL 关键字 | 不用 order, group |');
md += w('');

// ======== 4. 配置文件 ========
md += w('---');
md += w('');
md += w('## 4. 配置文件');
md += w('');
md += w('### 4.1 data-source.ts');
md += w('');
md += w('```typescript');
md += w('import { DataSource, DataSourceOptions } from "typeorm";');
md += w('import { config } from "dotenv";');
md += w('config();');
md += w('export const options: DataSourceOptions = {');
md += w('  type: "postgres",');
md += w('  host: process.env.DB_HOST || "localhost",');
md += w('  port: parseInt(process.env.DB_PORT || "5432", 10),');
md += w('  username: process.env.DB_USERNAME || "postgres",');
md += w('  password: process.env.DB_PASSWORD || "postgres",');
md += w('  database: process.env.DB_DATABASE || "happy_every_day",');
md += w('  entities: ["dist/**/*.entity{.ts,.js}"],');
md += w('  migrations: ["dist/database/migrations/*{.ts,.js}"],');
md += w('  migrationsTableName: "migrations_typeorm",');
md += w('};');
md += w('const ds = new DataSource(options);');
md += w('export default ds;');
md += w('```');
md += w('');
md += w('### 4.2 database.module.ts');
md += w('');
md += w('```typescript');
md += w('import { Module } from "@nestjs/common";');
md += w('import { TypeOrmModule } from "@nestjs/typeorm";');
md += w('import { options } from "./data-source";');
md += w('@Module({');
md += w('  imports: [TypeOrmModule.forRoot({ ...options, autoLoadEntities: true, migrationsRun: false })]');
md += w('})');
md += w('export class DatabaseModule {}');
md += w('```');
md += w('');
md += w('### 4.3 ormconfig.ts');
md += w('');
md += w('```typescript');
md += w('import { DataSource } from "typeorm";');
md += w('import { options } from "./src/database/data-source";');
md += w('export default new DataSource({');
md += w('  ...options,');
md += w('  entities: ["src/**/*.entity.ts"],');
md += w('  migrations: ["src/database/migrations/*.ts"],');
md += w('});');
md += w('```');
md += w('');
md += w('### 4.4 .env');
md += w('');
md += w('```env');
md += w('DB_HOST=localhost');
md += w('DB_PORT=5432');
md += w('DB_USERNAME=postgres');
md += w('DB_PASSWORD=postgres');
md += w('DB_DATABASE=happy_every_day');
md += w('```');
md += w('');

// ======== 5. 脚本配置 ========
md += w('---');
md += w('');
md += w('## 5. package.json 脚本配置');
md += w('');
md += w('```json');
md += w('"scripts": {');
md += w('  "mg:create":  "typeorm migration:create src/database/migrations/$npm_config_name",');
md += w('  "mg:gen":     "typeorm migration:generate -d ormconfig.ts -p src/database/migrations/$npm_config_name",');
md += w('  "mg:run":     "typeorm migration:run -d ormconfig.ts",');
md += w('  "mg:revert":  "typeorm migration:revert -d ormconfig.ts",');
md += w('  "mg:show":    "typeorm migration:show -d ormconfig.ts"');
md += w('}');
md += w('```');
md += w('');
md += w('使用: npm run mg:run   (短命名)');

// ======== 6. 初始化迁移 ========
md += w('');
md += w('---');
md += w('');
md += w('## 6. 初始化迁移模板');
md += w('');
